addons:
  hosts:
    - localhost
language: java
install: true
jdk: oraclejdk8
script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - sudo apt install oracle-java8-set-default
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - sudo chmod 755 ./install-jdk.sh -s
  - sudo ./install-jdk.sh -F 11 -L GPL -t jdk-11 -e -s
  - export ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME
  - export ORG_GRADLE_PROJECT_JAVA_11=$HOME/jdk-11
  - export JAVA_HOME=$ORG_GRADLE_PROJECT_JAVA_8
  - ./gradlew build
branches:
  only:
    - master
